$mod = SUPER

source=~/.config/hypr/mocha.conf
source=~/.config/hypr/keybinds.conf
source=~/.config/hypr/autostart.conf
source=~/.config/hypr/input.conf
source=~/.config/hypr/theme.conf
source=~/.config/hypr/workspaces.conf

# RuneLite
windowrule {
  name = runelite-tooltips
  match:class = ^(net-runelite-client-RuneLite)$
  match:title = ^win(.*)$
  no_initial_focus = true
}
