$op_lm = DP-1
$op_rm = DP-3
$op_tv = HDMI-A-1

$op_lm_res = 1920x1200, 0x0, 1
$op_rm_res = 1920x1200, 1920x0, 1
$op_tv_res = 3840x2160@165, 3840x0, 2, bitdepth, 10
$op_tv_res_hdr = 3840x2160@165, 3840x0, 2, bitdepth, 10, cm, hdr, sdrbrightness, 1.2, sdrsaturation, 1.05

monitor = $op_lm, disable
monitor = $op_rm, disable
monitor = $op_tv, $op_tv_res

bind = $mod CONTROL, period, exec, hyprctl --batch "keyword monitor $op_tv, $op_tv_res ; keyword monitor $op_lm, disable ; keyword monitor $op_rm, disable"
bind = $mod CONTROL, comma, exec, hyprctl --batch "keyword monitor $op_tv, disable; keyword monitor $op_lm, $op_lm_res; keyword monitor $op_rm, $op_rm_res"
bind = $mod CONTROL, minus, exec, hyprctl --batch "keyword monitor $op_tv, $op_tv_res_hdr ; keyword monitor $op_lm, disable ; keyword monitor $op_rm, disable"
